"""empty message

Revision ID: 1751147036cb
Revises: 33596888a96d
Create Date: 2021-01-22 17:16:02.740244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1751147036cb'
down_revision = '33596888a96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pedal', sa.Column(
                  'manufacturer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Pedal', 'Pedal',
                          ['manufacturer_id'], ['id'],
                          ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Pedal', type_='foreignkey')
    op.drop_column('Pedal', 'manufacturer_id')
    # ### end Alembic commands ###
