"""empty message

Revision ID: 33596888a96d
Revises:
Create Date: 2021-01-22 17:03:17.501397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33596888a96d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Manufacturer',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=True),
        sa.Column('image_link', sa.String(length=500), nullable=True),
        sa.Column('fb_link', sa.String(length=500), nullable=True),
        sa.Column('website_link', sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'Pedal',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=True),
        sa.Column('pedal_type', sa.String(length=120), nullable=True),
        sa.Column('new_price', sa.String(), nullable=True),
        sa.Column('used_price', sa.String(), nullable=True),
        sa.Column('image_link', sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pedal')
    op.drop_table('Manufacturer')
    # ### end Alembic commands ###
